# -*- coding: utf-8 -*-
# Часть 2: отключение Secure Boot по вендорам (7), ошибки (10), файловые системы (5).

VENDORS = [
("secure-boot-asus", "ASUS",
 "Отключить Secure Boot на ASUS: вход клавишами Del или F2, далее Advanced Mode (F7) — вкладка Boot — Secure Boot — OS Type: Other OS. Именно Other OS отключает проверку подписей.",
 ["Перезагрузите ПК и жмите Del/F2 до входа в UEFI.",
  "Нажмите F7 (Advanced Mode), откройте вкладку Boot.",
  "Пункт Secure Boot: в OS Type выберите Other OS (не Windows UEFI).",
  "Для загрузки MS-DOS дополнительно включите CSM/Legacy в Boot.",
  "F10 — сохранить и выйти."],
 "На части плат ASUS пункт Secure Boot появляется только после установки пароля администратора BIOS."),
("secure-boot-msi", "MSI",
 "Отключить Secure Boot на MSI: Del при старте — Settings — Security — Secure Boot — Disabled. Путь почти всегда через раздел Settings.",
 ["Войдите в BIOS клавишей Del.",
  "Откройте Settings — Security.",
  "Secure Boot — переключите в Disabled.",
  "Для MS-DOS включите Boot Mode: Legacy+UEFI и USB Boot.",
  "F10 — сохранить."],
 "На платах MSI с Click BIOS интерфейс графический — ищите иконку Security слева."),
("secure-boot-gigabyte", "Gigabyte",
 "Отключить Secure Boot на Gigabyte: Del — вкладка BIOS — Secure Boot — Disabled, плюс CSM Support: Enabled для загрузки DOS.",
 ["Del при включении, вкладка BIOS.",
  "CSM Support — Enabled (иначе Legacy-загрузка невозможна).",
  "Secure Boot — Disabled.",
  "В Boot Option выберите вашу флешку.",
  "F10 — сохранить и выйти."],
 "Gigabyte часто прячет Secure Boot, пока не выставлен CSM Enabled — делайте по порядку."),
("secure-boot-lenovo", "Lenovo",
 "Отключить Secure Boot на Lenovo: Enter/F1 (ThinkPad: F1, Idea: F2 или кнопка Novo) — вкладка Security — Secure Boot — Disabled.",
 ["ThinkPad: F1 при старте; IdeaCentre/ноутбуки: F2 или кнопка Novo.",
  "Вкладка Security — Secure Boot — Disabled.",
  "Вкладка Startup: UEFI/Legacy Boot — Both или Legacy Only для DOS.",
  "F10 — сохранить."],
 "На новых Lenovo с Windows 11 может потребоваться сначала отключить BitLocker, иначе диск не прочитается."),
("secure-boot-hp", "HP",
 "Отключить Secure Boot на HP: Esc — F10 (BIOS Setup) — Security — Secure Boot Configuration — снять галочку, ввести код подтверждения.",
 ["При включении жмите Esc, затем F10.",
  "Security — Secure Boot Configuration.",
  "Снимите Secure Boot, введите цифры подтверждения с экрана.",
  "Advanced — Boot Options: Legacy Support Enable для DOS.",
  "F10 — сохранить."],
 "HP требует ввод кода из 4 цифр — защита от случайного отключения."),
("secure-boot-dell", "Dell",
 "Отключить Secure Boot на Dell: F2 — Secure Boot — Secure Boot Enable: снять галочку (Disabled).",
 ["F2 при старте — раздел Secure Boot.",
  "Secure Boot Enable — Disabled.",
  "General — Boot Sequence: Legacy, добавьте USB.",
  "Apply — Exit."],
 "Dell показывает предупреждение об изменении — подтверждайте, это штатно."),
("secure-boot-acer", "Acer",
 "Отключить Secure Boot на Acer: F2 — Security — сначала задайте Supervisor Password, иначе пункт Secure Boot заблокирован.",
 ["F2 — вкладка Security.",
  "Set Supervisor Password — задайте пароль (запишите!).",
  "Появится Secure Boot — Disabled.",
  "Boot — Boot Mode: Legacy для MS-DOS.",
  "F10 — сохранить. Пароль потом можно сбросить тем же пунктом."],
 "Без пароля супервизора Acer не дает трогать Secure Boot — это их фирменная особенность."),
]

ERRORS = [
("oshibka-prevyshenie-4gb", "Cannot exceed 4GB for FAT16",
 "Бэкенд RMPARTUSB (MSDOSBOOT.exe) отказывается форматировать флешку больше 4 ГБ.",
 ["Флешка объемом больше 4 ГБ (например, 8/16/32 ГБ).",
  "MS-DOS загружается только с FAT16, а у FAT16 лимит раздела — 4 ГБ."],
 ["Возьмите флешку до 4 ГБ — это штатное требование, а не поломка.",
  "Либо разбейте большую флешку: первый раздел FAT16 до 4 ГБ сделать активным (инструкция — в статье про разделы)."]),
("oshibka-non-system-disk", "Non-System disk or disk error",
 "Классика: BIOS нашел диск, но загрузчика DOS на нем нет.",
 ["Флешка отформатирована без системных файлов (пропущен SYS).",
  "BIOS грузится не с той флешки."],
 ["Пересоздайте флешку через MBFU (SYS выполняется автоматически).",
  "Проверьте Boot Menu: выбирайте именно вашу флешку, а не HDD."]),
("oshibka-invalid-media", "Invalid media type",
 "DOS не понимает файловую систему раздела: обычно туда записали NTFS/exFAT вместо FAT.",
 ["Раздел отформатирован в NTFS или exFAT.",
  "Сбой таблицы разделов."],
 ["Пересоздайте флешку через MBFU — будет FAT16.",
  "Если нужно вручную: FDISK → удалить раздел → создать Primary DOS → FORMAT."]),
("oshibka-secure-boot-block", "Блокировка Secure Boot",
 "UEFI отказывается грузить неподписанный загрузчик MS-DOS.",
 ["Secure Boot включен (так по умолчанию на всех ПК с Windows 8+)."],
 ["Отключите Secure Boot в UEFI (инструкции по вендорам — в соседних статьях).",
  "Для MS-DOS также включите Legacy/CSM-режим."]),
("oshibka-no-os", "Missing operating system",
 "MBR есть, но активный раздел не загрузочный или системные файлы повреждены.",
 ["Активный флаг стоит не на том разделе.",
  "IO.SYS/MSDOS.SYS/COMMAND.COM удалены или побиты."],
 ["FDISK → назначить раздел активным (Set active partition).",
  "Либо пересоздать флешку через MBFU целиком."]),
("oshibka-himem", "HIMEM.SYS error / Missing HIMEM",
 "MS-DOS не видит расширенную память: драйвер не загрузился или железо без XMS.",
 ["Нет строки DEVICE=HIMEM.SYS в CONFIG.SYS.",
  "Конфликт менеджеров памяти."],
 ["Проверьте CONFIG.SYS: DEVICE=C:\\DOS\\HIMEM.SYS должен быть первым.",
  "На эмуляторах (DOSBox) XMS включается в конфиге: xms=true."]),
("oshibka-bad-command", "Bad command or file name",
 "Самая частая «ошибка» новичков: такого файла/команды нет в текущем каталоге и PATH.",
 ["Опечатка в имени.",
  "Программа лежит в другом каталоге, PATH не настроен."],
 ["Проверьте имя через DIR. Добавьте каталог в PATH в AUTOEXEC.BAT.",
  "Внешние команды (FORMAT, SYS) живут в C:\\DOS — он должен быть в PATH."]),
("oshibka-write-protect", "Write protect error",
 "Диск/флешка защищены от записи: переключатель Lock, права или сбой контроллера.",
 ["Физический локер на флешке/SD-адаптере.",
  "Атрибут read-only / права."],
 ["Снимите Lock. Проверьте ATTRIB. SD-карту попробуйте в другом адаптере."]),
("oshibka-disk-full", "Disk full / Insufficient disk space",
 "Место кончилось: дискета 1.44 МБ и маленький раздел забиты под завязку.",
 ["Копирование на переполненный диск.",
  "Временные файлы и кэш."],
 ["Освободите место: DEL *.TMP, чистите кэш. Большие пакеты ставьте частями."]),
("oshibka-ntvdm-64bit", "NTVDM и 16-битные программы на 64-бит Windows",
 "На 64-битной Windows DOS-программы не запускаются: NTVDM там нет (убран еще до Windows 11).",
 ["Попытка запустить .COM/.EXE 16-бит на Windows x64.",
  "Команды EDIT/DEBUG/EDLIN отсутствуют."],
 ["Используйте DOSBox или boot-флешку MBFU для настоящего DOS.",
  "Вариант: 32-битная Windows в виртуалке (там NTVDM жив)."]),
]

FILESYSTEMS = [
("fat16", "FAT16: пределы файловой системы DOS",
 "FAT16 — родная система MS-DOS: максимальный раздел 4 ГБ (на практике 2 ГБ без больших кластеров), файл — до 4 ГБ, имен 8.3. Именно поэтому MBFU требует флешки до 4 ГБ.",
 ["Раздел: до 4 ГБ (реально 2 ГБ).", "Файл: до 4 ГБ.", "Имена: 8.3, кириллицы нет.", "Загрузка DOS: да."],
 "Для MS-DOS альтернатив нет: только FAT16 (FAT12 — для дискет)."),
("fat32-dos", "FAT32 и DOS: совместимость",
 "FAT32 понимают MS-DOS 7.1+ (из Windows 95 OSR2/98) и FreeDOS, но не MS-DOS 5.0/6.22. Разделы до 2 ТБ, файлы до 4 ГБ.",
 ["Раздел: до 2 ТБ.", "Файл: до 4 ГБ.", "MS-DOS 6.22: не читает.", "Загрузка 6.22 с FAT32: невозможна."],
 "Если нужен DOS 6.22 — только FAT16. FAT32 — для DOS 7.x и обмена большими файлами."),
("exfat-dos", "exFAT и MS-DOS",
 "exFAT MS-DOS не понимает вообще: ни 5.0, ни 6.22, ни 7.x. Флешка из магазина почти всегда exFAT — ее надо переформатировать.",
 ["Раздел/файл: практически без лимитов.", "MS-DOS: не поддерживается.", "Ошибка Invalid media type — частый симптом."],
 "Перед созданием загрузочной флешки всегда проверяйте файловую систему."),
("ntfs-dos", "NTFS и MS-DOS",
 "NTFS для DOS — чужой: чтение только через драйвер NTFS4DOS (Avira), записи лучше избегать. Загрузиться с NTFS DOS не может.",
 ["Чтение: драйвер NTFS4DOS.", "Запись: рискованна.", "Загрузка: нет."],
 "Держите DOS-раздел FAT16, а NTFS-раздел — для обмена с Windows."),
("razmer-klastera", "Размер кластера FAT16",
 "Чем больше раздел FAT16, тем крупнее кластер: на 2 ГБ кластер 32 КБ — тысяча мелких файлов съест место впустую.",
 ["До 128 МБ: кластер 2 КБ.", "256–511 МБ: 8 КБ.", "1–2 ГБ: 16–32 КБ."],
 "Мелкие утилиты выгоднее держать на разделах поменьше."),
]
